# Generated by Django 3.0.5 on 2020-04-20 16:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_auto_20200419_1702'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book_history',
            unique_together={('user', 'book')},
        ),
    ]
