# Generated by Django 3.0.5 on 2020-04-20 16:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0005_auto_20200420_1611'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book_history',
            name='user_book_unique',
        ),
        migrations.AlterUniqueTogether(
            name='book_history',
            unique_together={('user', 'book')},
        ),
    ]
