# Generated by Django 3.0.5 on 2020-04-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200420_1615'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book_history',
            unique_together=set(),
        ),
    ]
