# Generated by Django 3.0.5 on 2020-04-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20200421_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_request',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
