# Generated by Django 3.0.5 on 2020-04-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_request',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
