# Generated by Django 3.0.5 on 2020-04-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20200421_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_comment',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
