# Generated by Django 3.0.5 on 2020-04-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_comment_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rate',
        ),
    ]
